CLASS zcx_stock_allocation DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC.
  PUBLIC SECTION.
    DATA message TYPE c LENGTH 220.
ENDCLASS.

CLASS zcx_stock_allocation IMPLEMENTATION.
ENDCLASS.
